language: node_js
node_js:
  - "8"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
success:
  - npm i -g codecov
  - codecov -t ${CODECOV_KEY}
cache: yarn
